
version: 2

models:
    - name: stg_ga
      description: "dbt 첫 학습"
      
sources:
  - name: sql_study
    database: sqlstudy-340606
    schema: sql_study
    tables: 
      - name: ga
      - name: accounts
      - name: login